
project_id = "mkpvrydcuugrrzmopgto"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

# Edge Functions Configuration
# The following edge functions are registered:
# They handle API calls from the front-end

[functions.search-clients]
verify_jwt = true

[functions.get-vehicles-by-client-id]
verify_jwt = true

[functions.get-process-by-id]
verify_jwt = true

[functions.get-client-by-id]
verify_jwt = true

[functions.list-infractions-by-process-id]
verify_jwt = true

[functions.list-infractions-by-vehicle]
verify_jwt = true

[functions.create-infraction]
verify_jwt = true

[functions.create-process]
verify_jwt = true

[functions.update-process]
verify_jwt = true

[functions.list-notification-templates]
verify_jwt = true

[functions.update-notification-template]
verify_jwt = true

[functions.delete-notification-template]
verify_jwt = true

[functions.consult-helena-fines]
verify_jwt = true

[functions.consult-infosimples-vehicle-fines]
verify_jwt = true

[functions.create-client]
verify_jwt = true

[functions.create-notification-template]
verify_jwt = true

[functions.create-vehicle]
verify_jwt = true

[functions.delete-notification-template]
verify_jwt = true

[functions.get-api-key-status]
verify_jwt = true

[functions.get-client-by-cpf-cnpj]
verify_jwt = true

[functions.get-user-search-history]
verify_jwt = true

[functions.update-client]
verify_jwt = true

[functions.update-notification-template]
verify_jwt = true
