// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkpvrydcuugrrzmopgto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rcHZyeWRjdXVncnJ6bW9wZ3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjM1NzMsImV4cCI6MjA2MDY5OTU3M30.yeL0iviOjmLj3sNyzkGgI3Pb-fHuWbV_gnc5O65aLBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);